# Nixpacks configuration for Railway deployment
# This is an alternative to using Dockerfile
# If railway.json is present, this file will be ignored

[phases.setup]
# Install required apt packages
aptPkgs = ["libcurl4", "libpq-dev", "postgresql-client"]

[phases.install]
# Install Ruby gems
cmds = [
    "gem install -N bundler:2.5.16",
    "bundle install"
]

[start]
# Start Rails server
cmd = "bundle exec rails server -b 0.0.0.0 -p ${PORT:-3000} -e ${RAILS_ENV:-production}"